products_api = [
    {
        'category':"Bracelets",
        'name':"Wave Decor Silver Bracelet",
        'image':'a1.jpg',
        'description':"Description",
        "price":930.00,
        "sizes":[ "X-Large" , '2X-Large' , "3X-Large"],
    },
    {
        'category':"Watches",  
        'name':"Rhinestone Decor Round Pointer Quartz Watch",
        'image':'a2.jpg',
        'description':"Description",
        "price":980.00,
        "sizes":[ "Large" , '2X-Large' , "3X-Large"],
    },
    {
        'category':"Jwelery", 
        'name':"Rhinestone Decor Silver Wedding Band For Women Bridal Wedding Fine Jewelry",
        'image':'a3.jpg',
        'description':"Description",
        "price": 290.00,
        "sizes":['X-Small','Small', "Medium" ,"Large"],
    },
    {
        'category':"Jwelery", 
        'name':"1pc Simple & Elastic & Silver Ring With Shiny Bead For Mix & Match",
        'image':'a4.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['X-Small' , 'Small',"Medium","Large"],
    },  
     {
        'category':"Jwelery", 
        'name':"1pc Vintage Green Dragonfly Ring 925 Sterling Silver Adjustable Finger Ring with Clear Cubic Zirconia Women Jewelry (packaged with box)",
        'image':'a5.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },  
    {
        'category':"Bracelets", 
        'name':"Infinity Symbol Decor Sterling Silver Chain Bracelet",
        'image':'a6.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Bracelets", 
        'name':"Name",
        'image':'a7.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Bracelets", 
        'name':"1pc Shiny S925 Sterling Silver Heart Shape Full Diamond, Versatile, Fashionable & Luxury Chain Bracelet For Sum",
        'image':'a8.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Bracelets", 
        'name':"1pc Fashionable Heart Decor Letter Detail Chain Bracelet For Women For Gift",
        'image':'a9.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Watches", 
        'name':"1pc Men Women Silver Zinc Alloy Strap Business Round Dial Quartz Watch, For Daily Life",
        'image':'a10.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Jwelery", 
        'name':"1pc Glamorous Pink Cubic Zirconia Heart Decor Sterling Silver Ring For Women For Wedding Party Jewelry Valentine's Day Gift",
        'image':'a11.jpg',
        'description':"Description",
        "price": 6.70,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Jwelery", 
        'name':"Rhinestone Decor Silver Wedding Band",
        'image':'a12.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    }, 
    {
        'category':"Bracelets", 
        'name':"Cubic Zirconia Bow Decor Sterling Silver Bracelet",
        'image':'a13.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    }, 
    {
        'category':"Earrings", 
        'name':"1pair Gorgeous Sparkle Earrings For Women s925 Sterling Silver Cubic Zirconia Flash Earrings Fine Jewelry Gift For Girls Prom Party Decor",
        'image':'a14.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    }, 
    {
        'category':"Watches", 
        'name':"Women's Watch Sets",
        'image':'a15.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Watches", 
        'name':"1pc Women Silver Zinc Alloy Strap Fashion Round Dial Quartz Watch, For Daily Life",
        'image':'a16.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    }, 
    {
        'category':"Jwelery", 
        'name':"Heart Decor Cuff Silver Ring",
        'image':'a17.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Large","3X-Large"],
    },
    {
        'category':"Bracelets", 
        'name':"1pc Fashionable Cubic Zirconia",
        'image':'a18.jpg',
        'description':"Description",
        "price": 10.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Jwelery", 
        'name':"1pc Cute Sterling Silver Two-tone Daisy Ring For Women, Suitable For Date And Party Gift In Summer",
        'image':'a19.jpg',
        'description':"Description",
        "price": 30.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Bracelets", 
        'name':"Name",
        'image':'a20.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Jwelery", 
        'name':"1pc Fashion Sterling Silver Infinity Symbol Detail Twist Ring For Women For Daily Decoration",
        'image':'a21.jpg',
        'description':"Description",
        "price": 330.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Watches", 
        'name':"Round Dial Pointer Silicone Watch",
        'image':'a22.jpg',
        'description':"Description",
        "price": 50.00,
        "sizes":['Small',"Medium","Large"],
    },
    {
        'category':"Watches", 
        'name':"2 Pcs Women's Watch Sets",
        'image':'a23.jpg',
        'description':"Description",
        "price": 20.00,
        "sizes":['Small',"Medium","Large"],
    },
]