# Generated by Django 4.2.1 on 2023-08-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
